
version: "3"

services:

  mb-rabbitmq:
    image: rabbitmq:3.12.6
    restart: always
    ports:
      - "5672:5672"
    networks:
      vpc:
        ipv4_address: 10.1.1.11

  mb-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    restart: always
    user: "1000:0"
    ports:
      - "9200:9200"
    volumes:
      - /baaso/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      vpc:
        ipv4_address: 10.1.1.21

  mb-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - /baaso/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ELASTICSEARCH_HOSTS: '["http://mb-elasticsearch:9200"]'
    networks:
      vpc:
        ipv4_address: 10.1.1.31

  mb-etcd:
    image: bitnami/etcd:3.5.9
    restart: always
    volumes:
      - /baaso/etcd/data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://mb-etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      vpc:
        ipv4_address: 10.1.1.41

networks:
  vpc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/16
