
version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.12.1
    restart: always
    ports:
      - "5672:5672"
    networks:
      vpc:
        ipv4_address: 10.1.3.11

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    restart: always
    user: "1000:0"
    ports:
      - "9200:9200"
    volumes:
      - /baaso/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      vpc:
        ipv4_address: 10.1.3.21

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - /baaso/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      vpc:
        ipv4_address: 10.1.3.31

networks:
  vpc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.1.0.0/16
