
version: "3"

services:

    mb-rabbitmq:
    image: rabbitmq:3.12.6
    restart: always
    ports:
      - "5672:5672"
    networks:
      - vpc

  mb-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    restart: always
    user: "1000:0"
    ports:
      - "9200:9200"
    volumes:
      - /baaso/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      - vpc

  mb-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - /baaso/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ELASTICSEARCH_HOSTS: '["http://10.1.1.21:9200"]'
    networks:
      - vpc

  ds-mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /baaso/mysql/data:/var/lib/mysql
      - /baaso/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - /baaso/mysql/mem.sh:/root/mem.sh:ro
    environment:
      MYSQL_ROOT_PASSWORD: "mysql@XTC"
    networks:
      - vpc

  ds-redis:
    image: redis:7.2.1
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /baaso/redis/data:/data
    networks:
      - vpc

  ds-minio:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /baaso/minio/data:/data
    environment:
      MINIO_ROOT_USER: "3KJLIOSFODNN0EXAMPO0"
      MINIO_ROOT_PASSWORD: "vJalrXUtnFEMI/I5MDENG/bPxRfmCYEXAMPLEHEY"
    command: server /data --console-address ":9001"
    networks:
      - vpc

  baaso-dbmigrator:
    image: baaso.platform/dbmigrator:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.DbMigrator/appsettings.json:/app/appsettings.json
    networks:
      - vpc

  baaso-auth:
    image: baaso.platform/auth:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.AuthServer/appsettings.json:/app/appsettings.json
    networks:
      - vpc

  baaso-identity:
    image: baaso.platform/identity:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.IdentityService/appsettings.json:/app/appsettings.json
    networks:
      - vpc

  baaso-administration:
    image: baaso.platform/administration:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.AdministrationService/appsettings.json:/app/appsettings.json
    networks:
      - vpc

  baaso-saas:
    image: baaso.platform/saas:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.SaasService/appsettings.json:/app/appsettings.json
    networks:
      - vpc

  baaso-cms:
    image: baaso.platform/cms:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.CmsService/appsettings.json:/app/appsettings.json
    networks:
      - vpc

  baaso-webgateway:
    image: baaso.platform/webgateway:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.WebGateway/appsettings.json:/app/appsettings.json
      - /baaso/baaso/BaaSo.Platform.WebGateway/ocelot.json:/app/ocelot.json
    networks:
      - vpc

  baaso-web:
    image: baaso.platform/web:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.Web/appsettings.json:/app/appsettings.json
    networks:
      - vpc

  baaso-publicwebgateway:
    image: baaso.platform/publicwebgateway:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.PublicWebGateway/appsettings.json:/app/appsettings.json
      - /baaso/baaso/BaaSo.Platform.PublicWebGateway/ocelot.json:/app/ocelot.json
    networks:
      - vpc

  baaso-publicweb:
    image: baaso.platform/publicweb:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.PublicWeb/appsettings.json:/app/appsettings.json
    networks:
      - vpc

  pae-nginx:
    image: nginx:1.25.2
    restart: always
    volumes:
      - /baaso/nginx/conf.d:/etc/nginx/conf.d
      - /baaso/nginx/www:/etc/nginx/www
      - /baaso/nginx/cers:/etc/nginx/cers
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - vpc

networks:
  vpc:
    driver: bridge
