version: "3"

services:

  baaso-dbmigrator:
    image: baaso.platform/dbmigrator:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.DbMigrator/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-auth:
    image: baaso.platform/auth:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.AuthServer/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-identity:
    image: baaso.platform/identity:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.IdentityService/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-administration:
    image: baaso.platform/administration:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.AdministrationService/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-saas:
    image: baaso.platform/saas:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.SaasService/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-cms:
    image: baaso.platform/cms:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.CmsService/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-webgateway:
    image: baaso.platform/webgateway:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.WebGateway/appsettings.json:/app/appsettings.json
      - /baaso/baaso/BaaSo.Platform.WebGateway/ocelot.json:/app/ocelot.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-web:
    image: baaso.platform/web:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.Web/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-publicwebgateway:
    image: baaso.platform/publicwebgateway:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.PublicWebGateway/appsettings.json:/app/appsettings.json
      - /baaso/baaso/BaaSo.Platform.PublicWebGateway/ocelot.json:/app/ocelot.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  baaso-publicweb:
    image: baaso.platform/publicweb:1.1.6
    volumes:
      - /baaso/baaso/BaaSo.Platform.PublicWeb/appsettings.json:/app/appsettings.json
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - vpc

  pae-nginx:
    image: nginx:1.25.2
    restart: always
    volumes:
      - /baaso/nginx/conf.d:/etc/nginx/conf.d
      - /baaso/nginx/www:/etc/nginx/www
      - /baaso/nginx/cers:/etc/nginx/cers
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      - vpc

networks:
  vpc:
    driver: bridge
