
version: "3"

services:

  mb-rabbitmq:
    image: rabbitmq:3.12.6
    restart: always
    ports:
      - "5672:5672"
    networks:
      vpc:
        ipv4_address: 192.168.1.11

  mb-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    restart: always
    user: "1000:0"
    ports:
      - "9200:9200"
    volumes:
      - /nas/file/baaso/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    networks:
      vpc:
        ipv4_address: 192.168.1.21

  mb-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.13
    restart: always
    ports:
      - "5601:5601"
    volumes:
      - /nas/file/baaso/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ELASTICSEARCH_HOSTS: '["http://192.168.1.21:9200"]'
    networks:
      vpc:
        ipv4_address: 192.168.1.31

networks:
  vpc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/16
