
version: "3"

services:

  ds-mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /nas/data/baaso/mysql/data:/var/lib/mysql
      - /nas/data/baaso/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - /nas/data/baaso/mysql/mem.sh:/root/mem.sh:ro
    environment:
      MYSQL_ROOT_PASSWORD: "mysql@XTC"
    networks:
      vpc:
        ipv4_address: 192.168.2.11

  ds-mongo:
    image: mongo:6.0.10
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /nas/data/baaso/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "mongo@XTC"
    networks:
      vpc:
        ipv4_address: 192.168.2.21

  ds-redis:
    image: redis:7.2.1
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /nas/data/baaso/redis/data:/data
    networks:
      vpc:
        ipv4_address: 192.168.2.31

  ds-minio:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /nas/file/baaso/minio/data:/data
    environment:
      MINIO_ROOT_USER: "3KJLIOSFODNN0EXAMPO0"
      MINIO_ROOT_PASSWORD: "vJalrXUtnFEMI/I5MDENG/bPxRfmCYEXAMPLEHEY"
    command: server /data --console-address ":9001"
    networks:
      vpc:
        ipv4_address: 192.168.2.41

networks:
  vpc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.0.0/16
